### ISSUE TITLE
Can't find Google Map initmap()

### ISSUE THREAD

**Issue by AuvEmma** [AuvEmma/MyToto#35]
![image](https://cloud.githubusercontent.com/assets/16655549/14285790/d6faf81a-fb1a-11e5-89c7-c87ecd5e766e.png)

I load the google map api script in the bottom of index.html.

index.html and initmap.js are in the same folder.

**Comment by AuvEmma** [comment]
Forgot to load initmap.js in index.html

![image](https://cloud.githubusercontent.com/assets/16655549/14286061/c483a078-fb1b-11e5-8742-7973a2469c37.png)

**Comment by cuivienor** [comment]
I was just commenting on this (: GJ
