### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetWidth' of null loading Google Map

### ISSUE THREAD

**Issue by AuvEmma** [AuvEmma/MyToto#36]
I am applying a google map style and this error message shows up.

**Comment by cuivienor** [comment]
give me a line reference @AuvEmma

**Comment by AuvEmma** [comment]
@pppetrov I moved bundle.js up before loading Google map and it works!:)

![image](https://cloud.githubusercontent.com/assets/16655549/14286900/bda4f786-fb1e-11e5-8121-1f0cb34c7dc6.png)

![image](https://cloud.githubusercontent.com/assets/16655549/14286920/d26a7b64-fb1e-11e5-8899-b684b1ac2245.png)

**Comment by cuivienor** [comment]
yep, but where are you applying the offsetWidth property?

**Comment by AuvEmma** [comment]
@pppetrov I found this map style online and copy the style array. I search it and there is no offsetWidth in that array. I will push the code now and it is in the initmap.js.
